version: '3'

services:
  postgres:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_USER: "${PGUSER}"
      POSTGRES_PASSWORD: "${PGPASSWORD}"
      POSTGRES_DB: "${PGDATABASE}"
    volumes:
    - dbdata:/var/lib/postgresql/data
    - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
    - "5432:5432"
  app:
    build:
      context: .
    ports:
    - "3000:3000"
    env_file:
    - ./.env

volumes:
  dbdata:
